config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'posts/new'
  # post 'posts' => 'posts#create'
  resources :posts
  root :to => 'homes#top'
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

  attachment :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.save
    redirect_to post_path(post.id)
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:location, :text, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb
<div class="cover align-middle">
  <div class="text-center">
    <p class="sub-title">〜旅行の思い出を共有する〜</p>
    <h1 class="title mb-2">Traveler</h1>
    <h2 class="btn btn-primary mr-2">新規登録</h2>
    <h2 class="btn btn-success ml-2">ログイン</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集する</h1>
<%= form_with model:@post, url:"/posts/#{@post.id}", local:true do |f| %>
<h4>旅行先</h4>
<%= f.text_field :location %>
<h4>感想</h4>
<%= f.text_area :text %><br>
<%= f.submit '保存' %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
  <p>旅行先</p>
  <span><%= link_to post.location, post_path(post) %></span>
  <p>画像</p>
  <%= attachment_image_tag post, :image, format: 'jpeg', size: '100x100' %>
<% end %>

app/views/posts/new.html.erb
<h1>新規旅行投稿</h1>
<%= form_with model: @post, url: '/posts', local: true do |f| %>
<h4>旅行先</h4>
<%= f.text_field :location %>
<h4>感想</h4>
<%= f.text_area :text %>
  <h4>画像</h4>
  &nbsp; &nbsp; <%= f.file_field :image %>
  <p></p>
<%= f.submit '投稿' %>
<% end %>

app/views/posts/show.html.erb
<h2>旅行先</h2>
<p><%= @post.location %></p>
<h2>感想</h2>
<p><%= @post.text %></p>
<h2>旅行先</h2>
<p><%= @post.location %></p>
<h2>感想</h2>
<p><%= @post.text %></p>
<h2>画像</h2>
<%= attachment_image_tag @post, :image, format: 'jpeg', size: "300x300" %><br>
<%= link_to '編集する', edit_post_path(@post.id) %><br>
<%= link_to '削除する', post_path(@post.id), data:{turbo_method: :delete, turbo_confirm:'本当に消しますか?'} %><br>
<%= link_to '投稿一覧ページへ', posts_path %>